parameters:
    cmobi_rabbitmq.connection.class: PhpAmqpLib\Connection\AMQPConnection
    cmobi_rabbitmq.lazy.connection.class: PhpAmqpLib\Connection\AMQPLazyConnection
    cmobi_rabbitmq.connection.factory.class: Cmobi\RabbitmqBundle\Amqp\ConnectionFactory

services:
    cmobi_rabbitmq.self_resource_checker:
        class: Symfony\Component\Config\Resource\SelfCheckingResourceChecker
        public: false
        tags:
            - { name: cmobi_rabbitmq.config_cache.resource_checker, priority: -990 }

    cmobi_rabbitmq.bc_resource_checker:
        class: Symfony\Component\Config\Resource\BCResourceInterfaceChecker
        public: false
        tags:
            - { name: cmobi_rabbitmq.config_cache.resource_checker, priority: -1000 }

    cmobi_rabbitmq.config_cache_factory:
        class: Symfony\Component\Config\ResourceCheckerConfigCacheFactory
        arguments:
            - []
        public: false

    cmobi_rabbitmq.connection.manager:
        class: Cmobi\RabbitmqBundle\Amqp\ConnectionManager
        arguments: ['%cmobi_rabbitmq.connections%']
        calls:
            - [setContainer, ["@service_container"]]