parameters:
    cmobi_rabbitmq.connection.class: Cmobi\RabbitmqBundle\Connection\CmobiAMQPConnection
    cmobi_rabbitmq.lazy.connection.class: Cmobi\RabbitmqBundle\Connection\CmobiAMQPLazyConnection
    cmobi_rabbitmq.connection.factory.class: Cmobi\RabbitmqBundle\Connection\ConnectionFactory

services:
    cmobi_rabbitmq.self_resource_checker:
        class: Symfony\Component\Config\Resource\SelfCheckingResourceChecker
        public: false
        tags:
            - { name: cmobi_rabbitmq.config_cache.resource_checker, priority: -990 }

    cmobi_rabbitmq.bc_resource_checker:
        class: Symfony\Component\Config\Resource\BCResourceInterfaceChecker
        public: false
        tags:
            - { name: cmobi_rabbitmq.config_cache.resource_checker, priority: -1000 }

    cmobi_rabbitmq.config_cache_factory:
        class: Symfony\Component\Config\ResourceCheckerConfigCacheFactory
        arguments:
            - []
        public: false

    cmobi_rabbitmq.connection.manager:
        class: Cmobi\RabbitmqBundle\Connection\ConnectionManager
        arguments: ['%cmobi_rabbitmq.connection.factories%']
        calls:
          - [setContainer, ["@service_container"]]

    cmobi_rabbitmq.message.handler:
        class: Cmobi\RabbitmqBundle\Queue\BaseQueueService

    cmobi_rabbitmq.healthcheck:
        class: Cmobi\RabbitmqBundle\Domain\Service\HealthCheckService
        arguments: ["@service_container"]