<?php

namespace Application\Infrastructure\Repository;

use Cmobi\RabbitmqBundle\Domain\Model\RpcQueueServer;
use \Doctrine\ORM\EntityRepository;

/**
 * CardBilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RpcQueueServerRepository extends EntityRepository
{
    /**
     * @param RpcQueueServer $rpcQueueServer
     * @return RpcQueueServer
     */
    public function getServer(RpcQueueServer $rpcQueueServer)
    {
        $rpcQueueServer = $this->findOneBy(['process' => $rpcQueueServer->getProcess()]) ?: $rpcQueueServer;
        $this->getEntityManager()->persist($rpcQueueServer);
        return $rpcQueueServer;
    }

    public function update()
    {
        $this->getEntityManager()->flush();
    }
}